// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Merch struct {
	ID    int32
	Name  string
	Price int32
}

type Purchase struct {
	ID           int32
	UserID       sql.NullInt32
	MerchID      sql.NullInt32
	PurchaseTime sql.NullTime
}

type Transaction struct {
	ID              int32
	FromUser        sql.NullInt32
	ToUser          sql.NullInt32
	Amount          int32
	TransactionTime sql.NullTime
}

type User struct {
	ID       int32
	Username string
	Password string
	Balance  int32
}
